"""将时间戳列改为带时区的 datetime

Revision ID: 986ddbdad1d7
Revises: 7e70abbef6ae
Create Date: 2026-02-24 22:52:57.374499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986ddbdad1d7'
down_revision: Union[str, None] = '7e70abbef6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_campaign_contact', type_='unique')
        batch_op.create_index(batch_op.f('ix_campaign_contacts_id'), ['id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)

    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.alter_column('phase',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pre', 'during', 'post', name='checklist_item_phase_enum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'done', 'skipped', name='checklist_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.alter_column('phase',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pre', 'during', 'post', name='checklist_phase_enum'),
               existing_nullable=False)

    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_committee_members_committee_id'), ['committee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_members_id'), ['id'], unique=False)

    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_committees_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committees_id'), ['id'], unique=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_communities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    with op.batch_alter_table('community_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_roles_id'), ['id'], unique=False)

    with op.batch_alter_table('content_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_analytics_id'), ['id'], unique=False)

    with op.batch_alter_table('content_communities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_content_community', type_='unique')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('contribution', 'release_note', 'event_summary', name='source_type_enum'),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('draft', 'reviewing', 'approved', 'published', name='status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.create_index(batch_op.f('ix_contents_id'), ['id'], unique=False)

    with op.batch_alter_table('ecosystem_contributors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_eco_contributor', type_='unique')
        batch_op.create_index(batch_op.f('ix_ecosystem_contributors_id'), ['id'], unique=False)

    with op.batch_alter_table('ecosystem_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecosystem_projects_id'), ['id'], unique=False)

    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('manual', 'excel_import', name='attendee_source_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('event_personnel', schema=None) as batch_op:
        batch_op.alter_column('assignee_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('internal', 'external', name='personnel_assignee_enum'),
               existing_nullable=False)
        batch_op.alter_column('confirmed',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'confirmed', 'declined', name='personnel_confirm_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('event_tasks', schema=None) as batch_op:
        batch_op.alter_column('task_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('task', 'milestone', name='task_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'task'"))
        batch_op.alter_column('phase',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pre', 'during', 'post', name='task_phase_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'pre'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('not_started', 'in_progress', 'completed', 'blocked', name='task_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'not_started'"))

    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'offline'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('draft', 'planning', 'ongoing', 'completed', 'cancelled', name='event_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))

    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('open', 'in_progress', 'closed', name='feedback_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('issue_links', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('github', 'gitcode', 'gitee', name='issue_platform_enum'),
               existing_nullable=False)
        batch_op.alter_column('issue_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('issue', 'pr', name='issue_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'issue'"))
        batch_op.alter_column('issue_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('open', 'closed', name='issue_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_participants_id'), ['id'], unique=False)

    with op.batch_alter_table('meeting_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_reminders_meeting_id'), ['meeting_id'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.alter_column('reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_meetings_committee_id'), ['committee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_status'), ['status'], unique=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('person_profiles', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('manual', 'event_import', 'ecosystem_import', name='person_source_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.drop_index('ix_person_profiles_email')
        batch_op.create_index(batch_op.f('ix_person_profiles_email'), ['email'], unique=True)
        batch_op.drop_index('ix_person_profiles_github_handle')
        batch_op.create_index(batch_op.f('ix_person_profiles_github_handle'), ['github_handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_profiles_gitcode_handle'), ['gitcode_handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_profiles_id'), ['id'], unique=False)

    with op.batch_alter_table('publish_records', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('wechat', 'hugo', 'csdn', 'zhihu', name='pub_channel_enum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'draft', 'published', 'failed', name='pub_status_enum'),
               existing_nullable=True)
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_publish_records_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_default_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('wechat_article_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wechat_article_stats_id'), ['id'], unique=False)

    with op.batch_alter_table('wechat_stats_aggregates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_article_category'), ['article_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_stats_aggregates_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_stats_aggregates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_id'))
        batch_op.drop_index(batch_op.f('ix_wechat_stats_aggregates_article_category'))

    with op.batch_alter_table('wechat_article_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wechat_article_stats_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('is_default_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('publish_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_records_id'))
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'draft', 'published', 'failed', name='pub_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('channel',
               existing_type=sa.Enum('wechat', 'hugo', 'csdn', 'zhihu', name='pub_channel_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('person_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_gitcode_handle'))
        batch_op.drop_index(batch_op.f('ix_person_profiles_github_handle'))
        batch_op.create_index('ix_person_profiles_github_handle', ['github_handle'], unique=False)
        batch_op.drop_index(batch_op.f('ix_person_profiles_email'))
        batch_op.create_index('ix_person_profiles_email', ['email'], unique=False)
        batch_op.alter_column('source',
               existing_type=sa.Enum('manual', 'event_import', 'ecosystem_import', name='person_source_enum'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_status'))
        batch_op.drop_index(batch_op.f('ix_meetings_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_meetings_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_community_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_committee_id'))
        batch_op.alter_column('reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('meeting_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_reminders_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_reminders_id'))

    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_participants_id'))

    with op.batch_alter_table('issue_links', schema=None) as batch_op:
        batch_op.alter_column('issue_status',
               existing_type=sa.Enum('open', 'closed', name='issue_status_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('issue_type',
               existing_type=sa.Enum('issue', 'pr', name='issue_type_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'issue'"))
        batch_op.alter_column('platform',
               existing_type=sa.Enum('github', 'gitcode', 'gitee', name='issue_platform_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'in_progress', 'closed', name='feedback_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'planning', 'ongoing', 'completed', 'cancelled', name='event_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'offline'"))

    with op.batch_alter_table('event_templates', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('event_tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('not_started', 'in_progress', 'completed', 'blocked', name='task_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'not_started'"))
        batch_op.alter_column('phase',
               existing_type=sa.Enum('pre', 'during', 'post', name='task_phase_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'pre'"))
        batch_op.alter_column('task_type',
               existing_type=sa.Enum('task', 'milestone', name='task_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'task'"))

    with op.batch_alter_table('event_personnel', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.Enum('pending', 'confirmed', 'declined', name='personnel_confirm_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('assignee_type',
               existing_type=sa.Enum('internal', 'external', name='personnel_assignee_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('event_attendees', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('manual', 'excel_import', name='attendee_source_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('ecosystem_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_projects_id'))

    with op.batch_alter_table('ecosystem_contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_contributors_id'))
        batch_op.create_unique_constraint('uq_eco_contributor', ['project_id', 'github_handle'])

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'reviewing', 'approved', 'published', name='status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('source_type',
               existing_type=sa.Enum('contribution', 'release_note', 'event_summary', name='source_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('content_communities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_content_community', ['content_id', 'community_id'])

    with op.batch_alter_table('content_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_analytics_id'))

    with op.batch_alter_table('community_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_roles_id'))

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.drop_index(batch_op.f('ix_communities_name'))
        batch_op.drop_index(batch_op.f('ix_communities_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committees_id'))
        batch_op.drop_index(batch_op.f('ix_committees_community_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('committee_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_members_id'))
        batch_op.drop_index(batch_op.f('ix_committee_members_email'))
        batch_op.drop_index(batch_op.f('ix_committee_members_committee_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.alter_column('phase',
               existing_type=sa.Enum('pre', 'during', 'post', name='checklist_phase_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'done', 'skipped', name='checklist_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('phase',
               existing_type=sa.Enum('pre', 'during', 'post', name='checklist_item_phase_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))

    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_contacts_id'))
        batch_op.create_unique_constraint('uq_campaign_contact', ['campaign_id', 'person_id'])

    # ### end Alembic commands ###
