"""Add multi-tenancy support

Revision ID: 993d1f15fe95
Revises: 
Create Date: 2026-02-08 11:05:29.010417

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa

# Pre-computed bcrypt hash for password "admin123"
# Generated using: passlib.context.CryptContext(schemes=["bcrypt"]).hash("admin123")
DEFAULT_ADMIN_PASSWORD_HASH = "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYuN.4OO3z."


# revision identifiers, used by Alembic.
revision: str = '993d1f15fe95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new tables first to ensure database file is created
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('community_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Create default community
    communities_table = sa.table(
        'communities',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('description', sa.Text),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )

    op.execute(
        communities_table.insert().values(
            id=1,
            name='Default Community',
            slug='default',
            description='Default community for existing content',
            is_active=True,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        )
    )

    # Create default admin user
    users_table = sa.table(
        'users',
        sa.column('id', sa.Integer),
        sa.column('username', sa.String),
        sa.column('email', sa.String),
        sa.column('hashed_password', sa.String),
        sa.column('full_name', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('is_superuser', sa.Boolean),
        sa.column('created_at', sa.DateTime),
    )

    op.execute(
        users_table.insert().values(
            id=1,
            username='admin',
            email='admin@example.com',
            hashed_password=DEFAULT_ADMIN_PASSWORD_HASH,
            full_name='Administrator',
            is_active=True,
            is_superuser=True,
            created_at=datetime.utcnow(),
        )
    )

    # Add admin user to default community
    community_users_table = sa.table(
        'community_users',
        sa.column('user_id', sa.Integer),
        sa.column('community_id', sa.Integer),
        sa.column('role', sa.String),
        sa.column('joined_at', sa.DateTime),
    )

    op.execute(
        community_users_table.insert().values(
            user_id=1,
            community_id=1,
            role='member',
            joined_at=datetime.utcnow(),
        )
    )

    # Check if old tables exist (after creating new tables to ensure DB file exists)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    contents_exists = 'contents' in existing_tables
    channel_configs_exists = 'channel_configs' in existing_tables

    # Handle contents table - either create from scratch or alter existing
    if not contents_exists:
        # Fresh install - create contents table with new schema
        op.create_table('contents',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=500), nullable=False),
            sa.Column('content_markdown', sa.Text(), nullable=True),
            sa.Column('content_html', sa.Text(), nullable=True),
            sa.Column('source_type', sa.Enum('contribution', 'release_note', 'event_summary', name='source_type_enum'), nullable=True),
            sa.Column('source_file', sa.String(length=500), nullable=True),
            sa.Column('author', sa.String(length=200), nullable=True),
            sa.Column('tags', sa.JSON(), nullable=True),
            sa.Column('category', sa.String(length=100), nullable=True),
            sa.Column('cover_image', sa.String(length=500), nullable=True),
            sa.Column('status', sa.Enum('draft', 'reviewing', 'approved', 'published', name='status_enum'), nullable=True),
            sa.Column('community_id', sa.Integer(), nullable=False),
            sa.Column('created_by_user_id', sa.Integer(), nullable=True),
            sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name='fk_contents_community', ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_contents_creator', ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('contents', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_contents_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_contents_community_id'), ['community_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_contents_created_by_user_id'), ['created_by_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_contents_scheduled_publish_at'), ['scheduled_publish_at'], unique=False)
    else:
        # Upgrading existing database - alter table
        with op.batch_alter_table('contents', schema=None) as batch_op:
            batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True))

        # Migrate existing contents to default community
        connection.execute(sa.text("UPDATE contents SET community_id = 1, created_by_user_id = 1"))

        with op.batch_alter_table('contents', schema=None) as batch_op:
            batch_op.alter_column('community_id', nullable=False)
            batch_op.create_index(batch_op.f('ix_contents_community_id'), ['community_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_contents_created_by_user_id'), ['created_by_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_contents_scheduled_publish_at'), ['scheduled_publish_at'], unique=False)
            batch_op.create_foreign_key('fk_contents_community', 'communities', ['community_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('fk_contents_creator', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    # Handle channel_configs table - either create from scratch or alter existing
    if not channel_configs_exists:
        # Fresh install - create channel_configs table with new schema
        op.create_table('channel_configs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('channel', sa.Enum('wechat', 'hugo', 'csdn', 'zhihu', name='channel_enum'), nullable=False),
            sa.Column('config', sa.JSON(), nullable=True),
            sa.Column('enabled', sa.Boolean(), nullable=True),
            sa.Column('community_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name='fk_channel_configs_community', ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('community_id', 'channel', name='uq_community_channel')
        )
        with op.batch_alter_table('channel_configs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_channel_configs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_channel_configs_community_id'), ['community_id'], unique=False)
    else:
        # Upgrading existing database - alter table
        with op.batch_alter_table('channel_configs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))

        # Migrate existing channel_configs to default community
        connection.execute(sa.text("UPDATE channel_configs SET community_id = 1"))

        with op.batch_alter_table('channel_configs', schema=None) as batch_op:
            batch_op.alter_column('community_id', nullable=False)
            batch_op.create_index(batch_op.f('ix_channel_configs_community_id'), ['community_id'], unique=False)
            batch_op.create_unique_constraint('uq_community_channel', ['community_id', 'channel'])
            batch_op.create_foreign_key('fk_channel_configs_community', 'communities', ['community_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contents_scheduled_publish_at'))
        batch_op.drop_index(batch_op.f('ix_contents_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_contents_community_id'))
        batch_op.drop_column('scheduled_publish_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('community_id')

    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_community_channel', type_='unique')
        batch_op.drop_index(batch_op.f('ix_channel_configs_community_id'))
        batch_op.drop_column('community_id')

    op.drop_table('community_users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_community_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.drop_index(batch_op.f('ix_communities_name'))
        batch_op.drop_index(batch_op.f('ix_communities_id'))

    op.drop_table('communities')
    # ### end Alembic commands ###
