"""add_sop_fields_to_checklist_items

Revision ID: b465db6a13ac
Revises: ffbd6edaf13b
Create Date: 2026-02-25 21:59:55.302075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b465db6a13ac'
down_revision: Union[str, None] = 'ffbd6edaf13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('responsible_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('responsible_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deadline_offset_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_template_items', schema=None) as batch_op:
        batch_op.drop_column('reference_url')
        batch_op.drop_column('estimated_hours')
        batch_op.drop_column('deadline_offset_days')
        batch_op.drop_column('responsible_role')
        batch_op.drop_column('is_mandatory')

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('responsible_role')
        batch_op.drop_column('is_mandatory')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
